### ISSUE TITLE
Feature request: live-translating a journal entry without creating a new journal entry

### ISSUE THREAD

**Issue by JiDW** [Meneltamar/fvtt-comprehend-languages#13]
Hello!

I love the idea of this module, thank you for creating it! 
I was wondering if it would be possible to have an optional non-persistent mode that could show the translation either in the same window or in a temporary popup without creating a new journal entry.

My use-case is that I mainly use the original material for prep-ing and playing, but I would like to be able to translate some pages on the fly during sessions to be able to read out loud some lore stuff or room description fluently. However, I would prefer not to clutter my world with extra entries that I will never use again if that make sense?

Thanks again for your work!

**Comment by Meneltamar** [comment]
Interesting idea!

In the same window wouldn't really work (without actually overwriting the text that is already there). I'll tinker around a bit with opening a Dialog-box instead. My concern is that this wouldn't work too well with longer Journals, but that remains to be seen!

**Comment by Meneltamar** [comment]
One question:
Would it also help you if the module would (optionally) directly open the translated Journal?
I.e. you click the "Translate" button, the original gets translated and the new one is just immediately opened after creation?

I am a bit hesitant about making the translations "ephemeral", due to the API usage quotas. It is fairly hard to get above the free quota with normal TTRPG play (I feel), but it's still something to keep in mind. If the translations are not persisted, people could be hitting their quotas way quicker.

**Comment by JiDW** [comment]
Thanks for taking this into consideration! 

I understand your concern about the API quota, I guess for my use case, it would not matter much since I would probably translate way fewer things than people who need to translate a whole adventure and save the result, so even if I had to translate twice the same entry that would still not be too much. However, I understand you are taking into account the possible need for support from people running out of quota and asking for your help, so I'll leave this decision up to you!

The selected hotkey things would work well for me, yes!
Journal entries are not that big in my adventures (WFRP 4e), but that would address your concern about huge journal entries in other adventures.

Opening the journal entry immediately could be enough too, I guess I could delete the entire "translation" folder at the end of each session while having a "live-like" translation workflow.

**Comment by Meneltamar** [comment]
I just released version 1.7 that includes the requested hotkey translations. Simply update the module, select some text and press Alt+T :)

**Comment by Meneltamar** [comment]
Thanks for your suggestion. Only after thinking about it did I realize that your proposed workflow will make my life so much easier while GMing as well!

I'll close this.

**Comment by JiDW** [comment]
Thank you very much!

**Comment by Nordiii** [comment]
Well, I would be interested in this feature! Using the Abomination Vaults premium Module which comes with preplaced Journal Notes it would be helpful if the original text could just be replaced by the translation!
