### ISSUE TITLE
Suggestions : Title Translation and Folder Translation ?

### ISSUE THREAD

**Issue by Nostalgia2046** [Meneltamar/fvtt-comprehend-languages#18]
Hello again, two suggestions I would like to propose : 

1. Would it be possible to have the title of the scene or actor etc be translated as well ? As seen in the capture. 

2. Also an other freaking cool feature would be to be able to batch translate a folder with all the journals inside of it in one click. 

Would be two awesome additions if possible of course; 

Thanks, loving it and sharing the module with a bunch of french Dm's. :)

![Capture](https://user-images.githubusercontent.com/97110801/214209175-f5f5615f-6f22-407d-b9b2-b4a444bfbb85.PNG)

**Comment by Meneltamar** [comment]
I just released a new version that allows the translation of titles and folders as well.

I also have the "Translate the whole folder with one click" thing on my radar, but I'll have to think a bit about it.

**Comment by Nostalgia2046** [comment]
And its freaking awesome ! Works like a charm !

Your module is definetely important for many dms. Talked about it yesterday to a dm friend and he was blown away haha



Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :mardi 24 janvier 2023 18:59
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Meneltamar/fvtt-comprehend-languages] Suggestions : Title Translation and Folder Translation ? (Issue #18)


I just released a new version that allows the translation of titles and folders as well.

I also have the "Translate the whole folder with one click" thing on my radar, but I'll have to think a bit about it.
