### ISSUE TITLE
Feature Request - Add "replace text on current" options when I click on the "translate" button 

### ISSUE THREAD

**Issue by p4535992** [Meneltamar/fvtt-comprehend-languages#25]
Since a journal often has links to other journals with specific uuid, I need to keep the journal I translate with the same uuid.
Is it possible to add when I click on the "translate" button make a dialog appear with the option to do text replace on the current journal ?
I think a confirmation dialog is more than enough to avoid miss clicks from the user.

**Comment by Meneltamar** [comment]
Implemented in the v2.1 release as a module setting to enable/disable.
