### ISSUE TITLE
[Feature] Compatibility with Monk's Enhanced Journal

### ISSUE THREAD

**Issue by Syrious** [Meneltamar/fvtt-comprehend-languages#26]
I'd really love this module to work with monk's journal. Currently when trying to translate a journal entry while monk's journal module is enabled, I get the error

```
comprehend-languages | The document type undefined is not supported!
(anonymous) @ main.js:1
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

The current workaround is to disable monk's module, translate everything and re-enable it afterwards.

**Comment by Meneltamar** [comment]
I tried to get it to work with Monk's a few months ago and completely
failed to do so with the current setup. I'd probably have to include a
completely different logic for the module for when MEJ is enabled in the
world, which I won't be able to do in the near future.
Not saying it won't happen, but if it does, it will definitely take quite a
bit of time.


Am Di., 27. Juni 2023 um 16:20 Uhr schrieb Syrious ***@***.***

**Comment by Syrious** [comment]
No biggie. Since MEJ can be disabled and re-enabled without losing everything, the workaround will do :)
