### ISSUE TITLE
"Failed to fetch" issue

### ISSUE THREAD

**Issue by Coyotito007** [Meneltamar/fvtt-comprehend-languages#28]
Hello,
Im using this excellent module with foundry 11 304 and mutant year 0 system / module.
I managed to translate practically the whole players' handbook but for some reason i cant translate one of the chapter: i get a "Failed to fetch" message for the whole section and every subsection of it.
Any idea (given that im very bad at coding) ?
Thx

**Comment by Meneltamar** [comment]
Could you attach the exported chapter to this ticket? (Rightclick the
Chapter in the sidebar, Export and then attach it here)

Unfortunately this sounds as if there is something "wrong" with the chapter
itself, but DeepL isn't very good at telling us what is wrong. If you send
it to me, I can see if I can spot anything.

Am Sa., 1. Juli 2023 um 22:26 Uhr schrieb Coyotito007 <
***@***.***>:

**Comment by Coyotito007** [comment]
Here it is. Thx a lot for your time.
[fvtt-JournalEntry-7.-the-ark-fgaem1wxadqFA4Oj.json.zip](https://github.com/Meneltamar/fvtt-comprehend-languages/files/11928804/fvtt-JournalEntry-7.-the-ark-fgaem1wxadqFA4Oj.json.zip)

**Comment by Meneltamar** [comment]
I was able to translate the whole thing without issues. I also split it
apart into separate Journals and translated them 1-by-1, which also worked.

Maybe you exceeded your monthly DeepL quota? You can check that here:
https://www.deepl.com/de/account/usage

I thought that error should be surfaced by the module if it is the case,
but maybe I introduced a bug somewhere in there...

Am So., 2. Juli 2023 um 08:16 Uhr schrieb Coyotito007 <
***@***.***>:

**Comment by Coyotito007** [comment]
Strange, i havent reached the quota.
Thx again for ur time though il keep looking into this.
