### ISSUE TITLE
V10 Compatibility

### ISSUE THREAD

**Issue by arkangel85** [Meneltamar/fvtt-comprehend-languages#8]
is possible to get the compatability to v10 foundry?

**Comment by Meneltamar** [comment]
v1.3 of the module is compatible with v10. What issues are you having?

**Comment by arkangel85** [comment]
sorry for delay, it simple doesn't work (yes api is correctly in)
![no-translate](https://user-images.githubusercontent.com/93746418/196993482-7d31ce92-e821-4577-a7f1-1f67a85104fb.gif)

**Comment by arkangel85** [comment]
yes
![image](https://user-images.githubusercontent.com/93746418/197024819-8721134f-505b-4233-8acd-f0496701155d.png)

**Comment by Meneltamar** [comment]
I have removed the Screenshot as it showed your API Key. Are you sure you copied the WHOLE api key? that one looked a bit weird compared to mine.

**Comment by arkangel85** [comment]
yes i'm sure, don't worry about delete i have already changed it (thx for fast support too) 
![image](https://user-images.githubusercontent.com/93746418/197027017-c98a8702-a43f-46df-9713-a22506892c8f.png)
don't worry about the image, i change it again after posting this answer

**Comment by Meneltamar** [comment]
did you add the :fx part at the end? it seems as if that was missing?
Otherwise, please send me a JSON of the Journal that you are trying to translate.

**Comment by arkangel85** [comment]
yes, how can i export the json?

**Comment by Meneltamar** [comment]
Right-Click the Journal in the right sidebar and click on Export Data
![grafik](https://user-images.githubusercontent.com/20552326/197109932-120c719e-b66b-4f25-989c-65e27d07ec24.png)

**Comment by arkangel85** [comment]
I suppose I have found the problem, if the paragraph to be translated has too many characters (i don't find the exact number of characters) the module does not work, on the contrary if I divide it into several pages it works correctly, do you think it is possible to fix it?

**Comment by Meneltamar** [comment]
I somehow assumed that was the issue.
I'll see if I can build a fix in the next few days!

Am Do., 27. Okt. 2022 um 16:46 Uhr schrieb Arka ***@***.***>:

**Comment by Meneltamar** [comment]
@arkangel85 I just pushed a new version (v1.4) that should fix the issue. At least it worked with your example without issue.
